# -*- coding: utf-8 -*-
"""Applications of pretrained LLMs .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eTF2CkCmhZgFvmnj4V6TPDkgvc43IfUr

**Text classification**
"""

# Install libraries first (run once)
# pip install transformers torch

from transformers import pipeline

# Load pretrained text classification model
classifier = pipeline("text-classification")

# Input text
text = "This product is really good and I like it."

# Perform classification
result = classifier(text)

# Print result
print(result)

"""**named entity recognition**"""

# Install once if needed
# pip install transformers torch

from transformers import pipeline

# Load pretrained NER model
ner = pipeline("ner", grouped_entities=True)

# Input text
text = "Elon Musk founded SpaceX in the United States in 2002."

# Perform NER
entities = ner(text)

# Print results
for entity in entities:
    print(entity)

"""**Question answering**"""

# Install once if needed
# pip install transformers torch

from transformers import pipeline

# Load pretrained NER model
ner = pipeline("ner", grouped_entities=True)

# Input text
text = "Elon Musk founded SpaceX in the United States in 2002."

# Perform NER
entities = ner(text)

# Print results
for entity in entities:
    print(entity)

"""**Text summarization**"""

# Install once if needed
# pip install transformers torch

from transformers import pipeline

# Load pretrained summarization model
summarizer = pipeline("summarization")

# Input text
text = """
Artificial Intelligence (AI) is transforming the world by enabling machines
to learn from data and perform tasks that usually require human intelligence.
AI is widely used in healthcare, education, finance, and transportation.
It improves efficiency and decision-making but also raises ethical and privacy concerns.
"""

# Generate summary
summary = summarizer(
    text,
    max_length=50,
    min_length=20,
    do_sample=False
)

print("Summary:", summary[0]['summary_text'])

