# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTXoyKGH9qvDhJI1Zo18viBwBAHva7X5
"""

import huggingface_hub
from huggingface_hub import hf_hub_download
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

text = input("Enter a sentence for sentiment analysis: ")

inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)
scores = torch.softmax(outputs.logits, dim=1)

label = torch.argmax(scores).item()
confidence = scores[0][label].item()

if label == 1:
    print("\nSentiment: POSITIVE")
else:
    print("\nSentiment: NEGATIVE")

print("Confidence Score:", round(confidence, 3))

