# -*- coding: utf-8 -*-
"""text similarity dectection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTXoyKGH9qvDhJI1Zo18viBwBAHva7X5
"""

import huggingface_hub
from huggingface_hub import hf_hub_download
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

sentence1 = input("Enter first sentence: ")
sentence2 = input("Enter second sentence: ")

emb1 = model.encode(sentence1, convert_to_tensor=True)
emb2 = model.encode(sentence2, convert_to_tensor=True)

similarity = util.cos_sim(emb1, emb2)

print("\nSimilarity Score:", round(similarity.item(), 3))

